### ISSUE TITLE
Parsing from hex numbers

### ISSUE THREAD

**Issue by OlegJakushkin** [NethermindEth/int256#34]
When NM client parses something like a Dictionary from JSON where input keys look like: `"0x0000000000000000000000000000000000000000000000000000000000000000"` we currently fail.

This leads to dirty hacks like re-implementing dictionary parser like they do [here](https://stackoverflow.com/a/7010231/1973207)  with explicit `(UInt256)BigInteger.Parse(skey.Substring(2), NumberStyles.HexNumber);` in it.

**Comment by master2023pyae-art** [comment]
#400
